# Docker Data-Only container to hold the ee-codeception library
# Version 0.1
# Author Darren Ethier
FROM busybox
MAINTAINER Darren Ethier (darren@eventespresso.com)
RUN mkdir /data
RUN chmod -R 755 /data
CMD ["/bin/sh"]